### ISSUE TITLE
Use for online Questionnaires

### ISSUE THREAD

**Issue by LinfordQ** [jmgirard/CARMA#10]
I'm guessing this is a longshot, but do you know if there might be any way to use CARMA on an online questionnaire? With all of the COVID stuff going on it would be nice if I could have people watch the video and respond through the web rather than coming into a lab. 

Thanks,

**Comment by jmgirard** [comment]
This use case is interesting, but it isn't really what CARMA was built for. You might look into alternatives like [PAGAN](https://pagan.institutedigitalgames.com/).
