### ISSUE TITLE
Files will open but will pause and not play video

### ISSUE THREAD

**Issue by taylorbrown125** [jmgirard/CARMA#12]
The files will open on CARMA but after about 20 seconds the videos will freeze and CARMA stops working. How do I fix this?

**Comment by jmgirard** [comment]
Does this happen when opening the videos in VLC (outside of CARMA)?

**Comment by taylorbrown125** [comment]
No, videos work fine outside of CARMA.

**Comment by jmgirard** [comment]
Do you hear any sort of error sound as the video freezes?
