### ISSUE TITLE
Unrecognized function or variable 'ctfroot' Error in => runtimeInitializationChecks.m at line 23

### ISSUE THREAD

**Issue by cpg300** [jmgirard/CARMA#14]
Hello, 

I have used Carma before on a desktop but recently switched to a Dell laptop for work. Since downloading it I have started receiving in CTFroot errors when opening the software. I have tried troubleshooting this issue in many ways, including fully re-installing all of Matlab 9.7 and Carma, but nothing seems to fix this error.

Do you have any recommendations on how to fix this issue?

Thank you

<img width="267" alt="Screenshot 2022-06-02 15 02 30" src="https://user-images.githubusercontent.com/106772468/171716828-0b0e8d9a-88c3-453c-9d36-21202a0d85a3.png">
.

**Comment by jmgirard** [comment]
This sounds more like an issue with your installation of MCR than an issue with CARMA. I recommend uninstalling any MATLAB Runtime Compiler versions you have on this computer and then trying to install CARMA again from this new link:
https://github.com/jmgirard/CARMA/releases/tag/v14.08
