### ISSUE TITLE
Error - Unrecognized property 'AutoPlay' for class 'COM.VideoLAN_VLCPlugin_2'

### ISSUE THREAD

**Issue by cjv3** [jmgirard/CARMA#17]
Current VLC 64 bit Installed

**Comment by cjv3** [comment]
![Carma-MATLAB error](https://user-images.githubusercontent.com/35934544/225991689-1da50d68-f27a-4845-b70c-a958f7325b9f.JPG)

**Comment by jmgirard** [comment]
Did you install the ActiveX Plugin during install and are you on Windows?

**Comment by cjv3** [comment]
Yes,VLC is installed with ActiveX and it is on Windows 10.

**Comment by jmgirard** [comment]
I had this same issue recently but it was solved when I reinstalled 64-bit VLC with ActiveX plugin and restarted. Can you please try this and let me know if the issue persists?

**Comment by cjv3** [comment]
I uninstalled and reinstalled VLC, only this time I checked "Delete cache and preferences" on the install and that seems to fix it. Thanks.

**Comment by jmgirard** [comment]
Glad it's working and thanks for the detailed response. Hopefully this will help others in the same situation.
