### ISSUE TITLE
collect ratings window unresponsive

### ISSUE THREAD

**Issue by neojel** [jmgirard/CARMA#2]
Hello,

I have downloaded and installed Carma, I have the correct VLC version (latest with Activex Plugin) but when I click on "collect ratings", while the large window opens, clicking anywhere just won't work. I hear an error sound. I cannot open a media file and I also cannot close the window, I need to ctrl alt del to close the program. I am wondering whether you know why this is the case?

Best wishes,
Alex

**Comment by jmgirard** [comment]
Definitely sounds like a bug I need to fix. Are you using mouse or joystick input?

**Comment by neojel** [comment]
This was using mouse/keyboard input.

**Comment by neojel** [comment]
update: I found a joystick in the office, tried it with that as well, but same problem.

**Comment by jmgirard** [comment]
Ok. Does the review window load?

**Comment by neojel** [comment]
It does, but then clicking anywhere on it, is similarly unresponsive. I can click on "Media" and then when I try to select Open Media File or Adjust Volume, it seems to encounter an error. Closing the window is the same, unresponsive. Clicking on any of the options of the Help drop-down menu works though!

**Comment by jmgirard** [comment]
Hmm.. This really sounds like a VLC problem. Can you please uninstall and reinstall the 64-bit version with ActiveX plugin from here? http://download.videolan.org/pub/videolan/vlc/last/win64/vlc-3.0.3-win64.exe

**Comment by neojel** [comment]
It worked! Thanks so much!

**Comment by jmgirard** [comment]
Glad to hear it! I added a few lines of code for detecting errors like this in the future. The new version CARMA v14.03 will include these changes.
