### ISSUE TITLE
Open Media not working correctly

### ISSUE THREAD

**Issue by Nteeeee** [jmgirard/CARMA#4]
Hi, 

I have downloaded and installed Carma, I have the correct VLC version (latest with Activex Plugin) but when I click on "collect ratings", once the window opens and I click on "open media file", nothing happens. 

It was working fine yesterday. I have tried to open different media files, nothing is  working. 

Any tips?

Thanks
Nicola

**Comment by Nteeeee** [comment]
Also I've uninstalled and reinstalled VLC - did not fix it.

**Comment by jmgirard** [comment]
So loading media files into CARMA worked yesterday, but not today? Did anything change between yesterday and today? Can you load the desired files into VLC directly?

**Comment by Nteeeee** [comment]
Yeah exactly. Nothing changed between yesterday and today. Yes I can load the files into VLC directly.

**Comment by jmgirard** [comment]
Any chance you could share one of the problematic files so I can try it?

**Comment by Nteeeee** [comment]
I charged computers and it seemed to fix the problem. 

The other day a participant was reviewing some footage using the joy stick. They pulled the joystick out accidentally and it caused the file to save somewhere but disappear, any idea where it would save if it was an error file?

**Comment by jmgirard** [comment]
Yes, the log files get created as CSV files in the "default folder," which can be configured using the Settings menu on the Collect window. Assuming you never changed the default directory, it would be either your Documents folder or the folder where CARMA was installed to.

https://github.com/jmgirard/CARMA/blob/d1722ea831eab6442cc407efb07976ce754425fb/fig_collect_vrjoy.m#L621
