### ISSUE TITLE
Video file displays outside of VLC player video frame

### ISSUE THREAD

**Issue by mgiorno** [jmgirard/CARMA#6]
Not sure why this is happening. I'm using Carma , MCT 9.4, and VLC 3.0.3 64-bit on a Dell XPS 13. The video plays back just fine and the rating scale works, but the video appears at the bottom left and goes over the edge of the VLC player video frame area on the Carma UI. any ideas?

**Comment by jmgirard** [comment]
A screenshot would help, but I think I know what you mean. My guess is that your laptop is zoomed in beyond its normal resolution. If you right-click the desktop (in Windows 10) and select "Display Settings" it should show you an option that says "Change the size of text, apps, and other items." If this option is set to anything other than 100%, the VLC window will not appear in the correct place.

![image](https://user-images.githubusercontent.com/6829033/64557945-b3bdab00-d310-11e9-9762-580504a6e1ad.png)

**Comment by mgiorno** [comment]
JM,

     Thanks. I figured it might have something to do with the display settings, but I wanted to ask first.

Mario Giorno

**Comment by jmgirard** [comment]
No problem. Let me know if this doesn't fix the problem.
