### ISSUE TITLE
Not allowing export of annotation csv file a rating video

### ISSUE THREAD

**Issue by mgiorno** [jmgirard/CARMA#7]
A student of one of the researchers I support was given the task of watching and rating a two and 40 minute video clip. When it finished he says he received an error saying he could export the rating data and the CARMA UI was frozen when he brought the laptop to me. Luckily CARMA did save a csv file suing the current data and time to name the file. however, when I viewed the ratings data it only showed a graph where it stayed at -100 and then spike to +100 at a few different moments on the timeline. Is there a limit to how long a video CARMA will allow users to rate? Also does CARMA keep the video file and the ratings data in memory the whole time the video is playing or does it at some time start dumping the data to a persistent file on disk?

**Comment by jmgirard** [comment]
Does the export always fail with an error, or just sometimes? There is no limit within CARMA for how long a video to be rated can be, but I have found that human annotators struggle to maintain attention for longer than 5-10 min. So I usually recommend chopping videos up into 5-10 min chunks to be rated individually. CARMA keeps the video file and the ratings data in memory during data collection and only writes it to the annotation file at the end (after some postprocessing steps). When an error occurs during data collection, the temporary data is dumped to a log file (without those postprocessing steps).
