### ISSUE TITLE
Nothing media opened after click "open" 

### ISSUE THREAD

**Issue by missymama** [jmgirard/CARMA#8]
After choosing a video file and clicking open in Carma, no media file was opened. My system is windows 10. 64bit operating system. What can possibly cause this problem?

**Comment by jmgirard** [comment]
Have you tried other media files? For instance, will it play the example video file from here?
https://github.com/jmgirard/DARMA/releases/download/v6.09/Example.Data.zip
Knowing this will help us narrow down if it is a problem with your specific file(s) or with the configuration of CARMA on your machine.

**Comment by missymama** [comment]
Hello! It finally opened. It probably took hours. Probably because my video size is big, often 2 -3 GB. Maybe I can try to downsize the file size to speed up the program.

**Comment by jmgirard** [comment]
I would recommend segmenting the videos to smaller clips (no more than 10 minutes or so) and compressing them using the h.264 codec. This can be done relatively easily with the [Handbrake](https://handbrake.fr/) program. Also, if you aren't already, be sure to load the file from the local drive and not from a USB drive, DVD drive, or web server as these may introduce delays.

**Comment by missymama** [comment]
I see. Thanks for the tips. I use box which is a virtual drive. I think that might delay the process.

**Comment by jmgirard** [comment]
Ok, keep me updated. Hopefully these steps will resolve things.

**Comment by missymama** [comment]
Sure! Thanks!
